//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputadoresITM.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IDVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public int IDCliente { get; set; }
        public int IDComputador { get; set; }
        public int NitAgencia { get; set; }

        [JsonIgnore] 
        public virtual Agencia Agencia { get; set; }
        [JsonIgnore] 
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore] 
        public virtual Computador Computador { get; set; }
    }
}
